replicaCount: 1
app:  
  namespace: default
  name: bestarion
  port: 3032
  image_pull_policy: IfNotPresent
image:
  name: 065140405948.dkr.ecr.ap-southeast-1.amazonaws.com/bestarion-demo-ecr
  tag: "8e568fdc"
service:
  type: LoadBalancer
